create table if not exists ai_long_term_memory (
    memory_id varchar(64) not null comment '长期记忆编号，系统生成',
    conversation_id varchar(64) not null comment '会话编号',
    invocation_id varchar(64) null comment '关联 Agent 单次调用编号',
    agent_name varchar(128) not null comment '智能体名称',
    user_id varchar(64) not null default 'mock-user' comment '用户编号，当前阶段使用 mock 值',
    customer_id varchar(64) not null default 'mock-customer' comment '客户编号，当前阶段使用 mock 值',
    operator_id varchar(64) not null default 'mock-operator' comment '操作员编号，当前阶段使用 mock 值',
    memory_type varchar(32) not null comment '记忆类型：MESSAGE、SUMMARY、PREFERENCE、FACT、RISK_NOTE',
    role varchar(32) not null comment '消息角色：USER、ASSISTANT、SYSTEM、TOOL',
    content longtext not null comment '长期记忆原文内容，当前允许明文存储',
    summary varchar(2048) null comment '长期记忆摘要，便于列表展示和后续上下文压缩',
    tags_json longtext null comment '标签 JSON，例如产品编码、业务域、风险类别',
    importance_score decimal(5,2) not null default 0.00 comment '重要性评分，0 到 100，后续用于长期记忆筛选',
    archived tinyint(1) not null default 0 comment '是否归档，0 否，1 是；归档不等于删除',
    metadata_json longtext null comment '扩展元数据 JSON',
    occurred_at timestamp not null default current_timestamp comment '记忆对应业务事件发生时间',
    created_at timestamp not null default current_timestamp comment '创建时间',
    primary key (memory_id),
    key idx_ai_long_term_memory_conversation_occurred (conversation_id, occurred_at),
    key idx_ai_long_term_memory_invocation_id (invocation_id),
    key idx_ai_long_term_memory_agent_type (agent_name, memory_type),
    key idx_ai_long_term_memory_user_customer (user_id, customer_id),
    key idx_ai_long_term_memory_archived_created (archived, created_at)
) default charset = utf8mb4 collate = utf8mb4_unicode_ci comment = 'AI 长期记忆表，永久保存历史对话和重要事实';
